name: xradar-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - pydata-sphinx-theme
  - pip
  - myst-parser
  - sphinx
  - sphinx-copybutton
  - nbsphinx
  - ipykernel
  - h5netcdf
  - h5py
  - lat_lon_parser
  - netCDF4
  - xarray
  - xarray-datatree>=0.0.10
  - xmltodict
  - dask
  - matplotlib-base
  - scipy
  - pip:
    - git+https://github.com/openradar/open-radar-data.git
