name: xradar-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.9,<3.12
  - pydata-sphinx-theme
  - pip
  - myst-parser
  - sphinx
  - sphinx-copybutton
  - sphinx-favicon
  - nbsphinx
  - ipykernel
  - h5netcdf
  - h5py
  - lat_lon_parser
  - netCDF4
  - open-radar-data>=0.1.0
  - pyproj
  - xarray<=2024.9.0
  - xarray-datatree>=0.0.10
  - xmltodict
  - cartopy
  - cmweather
  - dask
  - matplotlib-base
  - scipy
  - boto3
  - arm_pyart
  - ffmpeg
  - zarr
