name: xradar-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10,<3.14
  - pydata-sphinx-theme
  - pip
  - cffconvert
  - myst-parser
  - sphinx
  - sphinx-copybutton
  - sphinx-favicon
  - nbsphinx
  - ipykernel
  - h5netcdf
  - h5py
  - lat_lon_parser
  - netCDF4
  - open-radar-data>=0.1.0
  - pyproj
  - xarray>=2024.10.0
  - xmltodict
  - cartopy
  - cmweather
  - dask
  - matplotlib-base
  - scipy
  - boto3
  - arm_pyart
  - ffmpeg
  - zarr<3
  - pytest-xdist
  - pytest-cov
  - pre-commit
  - diff-cover
