name: xradar-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - pydata-sphinx-theme
  - pip
  - myst-parser
  - sphinx
  - sphinx-copybutton
  - xarray
  - xarray-datatree
  - pip:
    - bump2version
    - wheel
    - watchdog
    - flake8
    - coverage
    - twine
    - pytest
    - black
